### ISSUE TITLE
Is it possible to add support for librarian-ansible version numbers?

### ISSUE THREAD

**Issue by actionjack** [UnderGreen/ansible-role-mongodb#10]
[librarian-ansible](https://github.com/bcoe/librarian-ansible) which providers bundler like functionality support version handling by specifying version numbers by adding them to your meta/main.yml file e.g.:

```code
---
galaxy_info:
...
dependencies: []
version: 2.0.0
---
```
Is it possible to have the version numbers maintained in this playbook?

Cheers

@actionjack

**Comment by UnderGreen** [comment]
Fixed with https://github.com/UnderGreen/ansible-role-mongodb/commit/77736ceb7a04b87dba6352fcdbe3a61026771d1a.

**Comment by actionjack** [comment]
Thanks!

**Comment by duhast** [comment]
I'm using `librarian-ansible` too, thanks :+1:
