### ISSUE TITLE
role uses mongod.conf while installed package uses mongodb.conf

### ISSUE THREAD

**Issue by raleonardo** [UnderGreen/ansible-role-mongodb#108]
The role uses a hardwired definition /etc/mongod.conf while the installed package uses /etc/mongodb.conf.

Debian stretch (without systemd)
installing mongodb 3.2
in /etc/ninit.d/moongodb: CONF=/etc/mongodb.conf

**Comment by UnderGreen** [comment]
Role creates systemd unit or sysvinit unit which should use /etc/mongod.conf

**Comment by raleonardo** [comment]
but in this sysvinit script, '/etc/mongodb.conf' is defined instead, while role configurations go to  /etc/mongod.conf
