### ISSUE TITLE
net.http option is deprecated since 3.2 and removed since 3.6

### ISSUE THREAD

**Issue by jlegrand** [UnderGreen/ansible-role-mongodb#110]
https://docs.mongodb.com/manual/reference/configuration-options/#net-options

**Comment by erdenezul** [comment]
<pre>

net:
--
4 | bindIp: {{ mongodb_net_bindip }}
5 | {% if mongodb_major_version \| version_compare("3.6", "<") -%}
6 | http:
7 | enabled: {{ mongodb_net_http_enabled \| to_nice_json }}


</pre>
