### ISSUE TITLE
Galaxy Metadata Incorrect?

### ISSUE THREAD

**Issue by Rylon** [UnderGreen/ansible-role-mongodb#118]
Hi, hopefully a quick question for you, but is the Galaxy metadata correct? This page on the [Ansible Galaxy](https://galaxy.ansible.com/undergreen/mongodb) suggests you would install the plugin like this:

`ansible-galaxy install undergreen.mongodb`

But I get the following error:

`[WARNING]: - undergreen.mongodb was NOT installed successfully: - sorry, undergreen.mongodb was not found on https://galaxy.ansible.com.`

Do you have any recommendations please?

Thanks!

**Comment by UnderGreen** [comment]
@Rylon maybe it is a transient error with galaxy. I haven't changed anything, should works as it worked before.

**Comment by gaetanfl** [comment]
@UnderGreen Didn't you rename your ansible user name from greendayonfire to undergreen ?

**Comment by Rylon** [comment]
@UnderGreen hi! Just to let you know, it does now work again! I think you must be right in that it was an error with Galaxy itself then. Sorry to have bothered you 👍
