### ISSUE TITLE
Add APT key fails

### ISSUE THREAD

**Issue by dinony** [UnderGreen/ansible-role-mongodb#122]
Hi,

I'm using: ansible 2.6.1 with Vagrant 2.1.2.
Target box is debian 9.4.0.
Seems to happen since galaxy package name change :)

![mongodb-issue](https://user-images.githubusercontent.com/2547965/43157512-8ee19dd2-8f7d-11e8-8339-1cdfff13a241.jpg)

Do you have an idea what could be wrong? 
Thanks!

**Comment by lakiboy** [comment]
This is most likely due to 11371 port blocking.

**Comment by boutetnico** [comment]
I have the same issue as @dinony.
I got it working with:
```
mongodb_apt_keyserver: hkp://keyserver.ubuntu.com:80
```

**Comment by rockandska** [comment]
We got the same issue but it is relate to https://github.com/ansible/ansible/issues/31691 and the fact we use a proxy on the guest server.
It will be nice to see implemented a workaround to by pass this limitation

**Comment by UnderGreen** [comment]
gpg keyservers infrastructure can be so flaky sometimes. The issue is not related to this role.
