### ISSUE TITLE
Upstream mongodb_replication module

### ISSUE THREAD

**Issue by danihodovic** [UnderGreen/ansible-role-mongodb#127]
Hi,

Great work on the [mongodb_replication](https://github.com/UnderGreen/ansible-role-mongodb/blob/master/library/mongodb_replication.py) module. Are there any plans to get this upstream into the Ansible repo?  I think there is value in extracting that module on its own so that we can use it regardless of using this role.

**Comment by Chrislevi** [comment]
https://docs.ansible.com/ansible/latest/modules/mongodb_replicaset_module.html#mongodb-replicaset-module
