### ISSUE TITLE
Systemd is reloaded every time a playbook is run.

### ISSUE THREAD

**Issue by Rylon** [UnderGreen/ansible-role-mongodb#130]
There is a duplicate of the handler inside the tasks file, here:

https://github.com/UnderGreen/ansible-role-mongodb/blob/0dd9e517c3faeb173c19f58587ded41236f0b276/tasks/install.debian.yml#L61

This results in Systemd being reloaded every time the playbook is run, even if no changes were made that would require this.

**Comment by tekenny** [comment]
I'm experiencing this as well on Ubuntu 16.04
I also noticed the following relating to line 65.
 [WARNING]: flush_handlers task does not support when conditional

**Comment by UnderGreen** [comment]
Fixed in master
