### ISSUE TITLE
Pymongo error

### ISSUE THREAD

**Issue by ftx** [UnderGreen/ansible-role-mongodb#132]
Hello,

I use ubuntu 18.04 and mongodb 3.6, all install is ok, but when i want to do the replicaset, i have this error 👍 

pymongo.errors.ServerSelectionTimeoutError: No servers found yet

I have test many versions of pymongo but 3.6 is the minimum...

Thanks

**Comment by ftx** [comment]
OK for me, just a problem with interconnexion and mongodb_login_host setting.

**Comment by EugeneKostrikov** [comment]
Yey thanks, mongodb_login_host and mongodb_replication_params were not updated with new addresses indeed.
