### ISSUE TITLE
User and admin account documentation clarification

### ISSUE THREAD

**Issue by ctlaux** [UnderGreen/ansible-role-mongodb#133]
I'm requesting a clarification of the documentation:

There are different ways of creating different types of users and accounts with this role, what are the differences between them? I thought users are associated with dbs, but what are the admin users associated with? And the two examples in the documentation are not heading in the same direction...

It turns out I can't log into any one of the created accounts after running setup with this role, I'm not sure how to debug this...

**Comment by pdreker-pa** [comment]
It seems like when using the role to setup a *single node replicaset*, that the users are not created or something goes wrong with that. Also when re-running the role on an already setup mongodb "weird things happen".

For single node mongo setups I had to remove all replication references from the vars YAML.

Without `mongodb_login_host, mongodb_replication_params, mongodb_replication_replset, mongodb_replication_replindexprefetch, mongodb_replication_oplogsize` defined, the authentication works with the configured users.

As for the documentation: I understand the `siteRootAdmin` and `siteUserAdmin` are the "master" users, which can be used to further setup mongo, if there are not DB users defined.
