### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by ctlaux** [UnderGreen/ansible-role-mongodb#135]
I'm receiving this error, seem to be missing a python module:

```
TASK [undergreen.mongodb : Replication configuration]

Traceback (most recent call last):
File "/tmp/ansible_sb1q04r9/ansible_module_mongodb_replication.py", line 159, in <module>
import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'```

Installing configparser (lower case) does not work, so which python3 module should I install on the server? I know there are many providers for this parser... I'm using python3 on the server, hope that is ok.

**Comment by ctlaux** [comment]
Ok, so simply using python2 instead of python3 made the ConfigParser available.

**Comment by jakubgs** [comment]
Since the script depends on python 2 instead of 3 it should be made explicit in the shebang:
https://github.com/UnderGreen/ansible-role-mongodb/blob/4f2afe4a0b212c0ddbd563928d8217a40f7bbfe2/library/mongodb_replication.py#L1
It should be:
```bash
#!/usr/bin/env python2
```
