### ISSUE TITLE
Stuck during mongodb installation task (squash_actions is deprecated)

### ISSUE THREAD

**Issue by Matroshiro** [UnderGreen/ansible-role-mongodb#136]
Hello,

I find myself stuck during mongodb installation task because of this warning : 

![ansible_issue](https://user-images.githubusercontent.com/36643208/47304491-1a69a580-d627-11e8-9897-572e19d8ff00.png)

Do you know how I could fix this warning ? I'm using ansible version 2.7.

Best regards

**Comment by UnderGreen** [comment]
Just follow the advise from the warning:
name: ["{{mongodb_package}}", "numactl"]

**Comment by Matroshiro** [comment]
Finally it wasn't an bid deal, i just had to wait a long time due to my slow connection. Thanks anyway :)
