### ISSUE TITLE
Is it possible to get ip's of ec2 instances which spin up by terraform

### ISSUE THREAD

**Issue by ChinthakaHasakelum** [UnderGreen/ansible-role-mongodb#140]
Is there any way to fill inventory file with ip's of each host? (Since ec2 instances are spin up by terraform)

`[mongo_master]
192.158.56.2 mongodb_master=True # it is't a really master of MongoDB replica set,
                                 # use this variable for replica set init only
								 # or when master is moved from initial master node

[mongo_replicas]
192.168.56.3
192.168.56.4

[mongo:children]
mongo_master
mongo_replicas`

**Comment by UnderGreen** [comment]
1. Create inventory file with empty `mongod_master` `mongo_replicas` groups.
2. Use [add_host](https://docs.ansible.com/ansible/latest/modules/add_host_module.html) in your playbook to add newly initialized nodes to groups above.
