### ISSUE TITLE
Debian Stretch / MongoDB 4.0 - systemd unit file conflict

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [UnderGreen/ansible-role-mongodb#162]
Hello,

Systemd unit files are provided by Debian mongodb-org-server package, and there is no need to install another one using ansible. 

* /lib/systemd/system/mongodb.service, installed by ansible
* /lib/systemd/system/mongod.service, installed by package

Immediately after provisioning MongoDB 4.0, "mongod.service" is used, and "mongodb.service" is inactive. After server reboot, "mongodb.service" is used (or it was my pure luck). So we have small conflict here.

**Comment by boutetnico** [comment]
I can confirm this issue.

The difference between these files is `mongodb.service` is invoking `mongod` using `numactl` which is, in my understanding, the reason behind this custom systemd service file. This is a recommended setting from [official MongoDB documentation](https://docs.mongodb.com/manual/administration/production-notes/).

I see few options to resolve this:

1) Disable `mongod.service` (might be error prone when restarting the service manually)
2) Delete `mongod.service`
3) Overwrite `mongod.service` with the template provided in this role
4) Same as 3) + Make installing `NUMA` & custom systemd unit file optional so one can disable that.

I would go for option 4 and could prepare a PR for that.

@UnderGreen @TomaszUrugOlszewski What do you think?

**Comment by TomaszUrugOlszewski** [comment]
Hello @boutetnico 

As role user, I don't need custom MongoDB unit file, and one provided by package is good enough. 

So another option that I would like to add:
5. Specify additional variable that allows to overwrite service name (to mongodb) and disable uploading custom mongod unit file 

If "5" is false, then option 4 looks like the best solution with custom MongoDB unit file.

**Comment by UnderGreen** [comment]
@TomaszUrugOlszewski can you check that the problem solved with latest master?
