### ISSUE TITLE
Custom repo

### ISSUE THREAD

**Issue by dragon-bn** [UnderGreen/ansible-role-mongodb#172]
Hello
Can you add the ability to enable or disable deposits ? Or ability to configure repositories with variables ?
Indeed, the role seems incompatiblie with the use of personalized deposits.
Thank you.

**Comment by UnderGreen** [comment]
Hey @dragon-bn. Thank you for your question.
In vars directory you can find how I define repositories for major OS distributions. You can redefine them in your variables file. Something like:
```
mongodb_repository:
  "3.4": "deb http://myrepo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.4 multiverse"
  "3.6": "deb http://myrepo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
  "4.0": "deb http://myrepo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.0 multiverse"
  "4.2": "deb http://myrepo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.2 multiverse"
```

**Comment by dragon-bn** [comment]
Thanks for your response.

**Comment by UnderGreen** [comment]
I assume I can close it. Feel free to reopen if you still expecting another answer.
