### ISSUE TITLE
Update Mongo version to 4.2

### ISSUE THREAD

**Issue by EvgeniiProkofevItomych** [UnderGreen/ansible-role-mongodb#174]
Hi. Could you update your Ansible role to use recent Mongo version? I've tried to change it locally, but failed.

**Comment by psabhay** [comment]
Hey @EvgeniiProkofevItomych I am working on it. Will create a PR once I have tested it.

**Comment by EvgeniiProkofevItomych** [comment]
Thank you!

**Comment by bonesoul** [comment]
is it done already?
