### ISSUE TITLE
Mongo 3

### ISSUE THREAD

**Issue by memelet** [UnderGreen/ansible-role-mongodb#18]
I'm trying to install mongo 3, but with the mongodb_repository variable being defined in vars/ its locked down. Specifying a mongodb_repository value does work:

```
  roles:
    - role: mongodb
      mongodb_repository: "deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.0 multiverse"
```
I needed to first comment out the contents of vars/*.yml. 

Its not clear to me (ansible newbee) how to make default values that are {{ansible_distribution}} dependent.

**Comment by memelet** [comment]
It also looks some behavior changes with 3?

```
vagrant@bastion-vagrant:~$ /usr/bin/mongod --config /etc/mongod.conf
2015-04-23T10:44:12.729+0000 F CONTROL  Failed global initialization: BadValue syslog is not allowed when logpath is specified
```

This seems a bit restrictive on mongos part as the value of 'mongodb_conf_syslog' is false.

**Comment by UnderGreen** [comment]
I need a lot of free time to implement Mongo 3 support. Maybe next week I will find this time.

**Comment by memelet** [comment]
Well, so far for non-replicaset the only problems I encountered I mentioned above. Tomorrow I will get the replica set running and will report back.

If been reading many many ansible roles in the last week, and this one seems quite well done. (I'm converting a large system over from chef.)

**Comment by buunguyen** [comment]
Any update on Mongo 3 support? Thanks!

**Comment by dluksza** [comment]
+1 for mongo 3 support

**Comment by kajisaap** [comment]
Not realising this good work by @UnderGreen , I started out to build MongoDB role on my own few months back. As soon as I stumbled on this particular role, I scraped 90% of mine and started copying :). So far Mongo 3 without authentication/authorisation is working fine but when I introduce auth part, the role breaks down. It came down to `mongodb_replication.py` script and `mongodb_user` action. I am currently researching the later. @UnderGreen , it would nice to get some input on `mongodb_replication.py` module regarding compatibility with MongoDB 3.

**Comment by quellhorst** [comment]
Mongo 3.2 is out now with a new default storage engine. Would be wonderful to be able to use your role for this.

**Comment by jordiclariana** [comment]
Check out my fix: https://github.com/jordiclariana/ansible-role-mongodb/commit/6f75f3f49e7a4886a7a49d1eaddc5356b0e2fc8e

I hope it will be merged.

**Comment by UnderGreen** [comment]
Hello guys.

Have a free time and started to refactor role for supporting Mongo 3.x.
https://github.com/UnderGreen/ansible-role-mongodb/tree/mongo3x_support

**Comment by dan-perron** [comment]
@UnderGreen I've pulled your mongo3 tree and was able to get replication up and running with it. I did run into a couple problems:
* `BadValue syslog is not allowed when logpath is specified` (fixed with @jordiclariana 's fix + copying it into mongod_init.conf.j2)
* replication.yml references `mongodb_login_port` which isn't used anywhere else in this module. I assume it should be `mongodb_conf_port`

**Comment by dan-perron** [comment]
Oh, the removal of 
```
- name: stop mongod to change mongo uid/gid
  service: name=mongod state=stopped
  when: (mongodb_gid is defined) or (mongodb_uid is defined)
```
also caused startup failures in my configuration. (and the related `start mongod after changing uid/gid`)

**Comment by UnderGreen** [comment]
Implemented!
