### ISSUE TITLE
task "Configure mongodb" - template error while templating string: no test named 'version'

### ISSUE THREAD

**Issue by fabianochagas** [UnderGreen/ansible-role-mongodb#189]
Greetings! 
I'm having this error while running the playbook:
"AnsibleError: template error while templating string: no test named 'version'...."

It is on the mongodb.conf template used by the task _Configure mongodb_ (configure.yml)
![image](https://user-images.githubusercontent.com/15588061/68045457-eb612780-fcaf-11e9-97b1-58a80d154521.png)

We are using Mongodb 3.4 over a ubuntu 16.4 and python 2.7, and the role's version is v2.6.0

Did anyone already have this issue?
Thanks in advance!

**Comment by herkyl** [comment]
I got the same error on Ansible 2.4 but after updating to 2.5 it disappeared.

**Comment by fabianochagas** [comment]
Thanks for the help, bro. 
It worked!

**Comment by UnderGreen** [comment]
@fabianochagas FYI minimum Ansible version is [2.5](https://github.com/UnderGreen/ansible-role-mongodb/blob/master/meta/main.yml#L9).
