### ISSUE TITLE
Unable to create users with recent mongodb version

### ISSUE THREAD

**Issue by miholeus** [UnderGreen/ansible-role-mongodb#212]
The script gives me the following error

```
Unable to add or update user: Use of SCRAM-SHA-256 requires undigested passwords
```

That bug was fixed with modern pymongo version. So we need to update to it.

**Comment by miholeus** [comment]
Created PR #213

**Comment by dorianm** [comment]
Your fix works great ! Thank you @miholeus :)

**Comment by UnderGreen** [comment]
Fixed in the latest release.
