### ISSUE TITLE
Not authorized for insert on admin.system.users

### ISSUE THREAD

**Issue by sebas5384** [UnderGreen/ansible-role-mongodb#23]
The error happens when is provisioned by the second time.
I Did a previous research but I got nothing, so I would appreciate some help :)
The playbook is running using Vagrant with Ubuntu Trusty as OS.
```shell
......

TASK: [greendayonfire.mongodb | wait MongoDB port is listening] ***************
ok: [default]

TASK: [greendayonfire.mongodb | create administrative user siteUserAdmin port=yes] ***
ok: [default] => (item={'password': u'NmL6@Rjs', 'name': u'mongoAdmin', 'roles': 'userAdminAnyDatabase'})

TASK: [greendayonfire.mongodb | create administrative user siteRootAdmin port=yes] ***
failed: [default] => (item={'password': u'kLx#m$wb@cw', 'name': u'mongoRoot', 'roles': 'root'}) => {"failed": true, "item": {"name": "mongoRoot", "password": "nOffi4sss@d", "roles": "root"}}
msg: not authorized for insert on admin.system.users

FATAL: all hosts have already failed -- aborting
....
```
_The passwords were changed ;)_

**Comment by UnderGreen** [comment]
Hello

I am rewriting auth and replication stuff. On Monday I will create new release for this role.

**Comment by sebas5384** [comment]
@UnderGreen awesome news!! I would love to have this role as part of my NodeJs Ansible stack :+1:

**Comment by UnderGreen** [comment]
Hi,
You can try refactored version here:
https://github.com/UnderGreen/ansible-role-mongodb/tree/refactoring

**Comment by UnderGreen** [comment]
You should add `mongodb_master=True` for 'master' node if you want to initialize replica set.
Something like:
```ini
[mongo_master]
192.158.56.2 mongodb_master=True

[mongo_replicas]
192.168.56.3
192.168.56.4
```

**Comment by UnderGreen** [comment]
Merged into master

**Comment by sebas5384** [comment]
Hey @UnderGreen! wow that was quick, thank you!
I would give it a try.

**Comment by sebas5384** [comment]
It worked perfectly! thanks!
Whenever you can update the project's Ansible Galaxy version, differs from the Git.

**Comment by UnderGreen** [comment]
Hi!
I don't see difference in version with Galaxy and Github. 1.4.3 is the same.
