### ISSUE TITLE
Hugepage configuration fail on Debian 7

### ISSUE THREAD

**Issue by VoidAndAny** [UnderGreen/ansible-role-mongodb#28]
The task "greendayonfire.mongodb | Create sysfs config" fail with the following error : 
Destination directory /etc/sysfs.d does not exist

Effectively on Debian 7 this directory doesn't exist.

According to the mongodb documentation (http://docs.mongodb.org/manual/tutorial/transparent-huge-pages/#in-etc-rc-local-alternate) in order thy activate hugepage, the file to modify is /etc/rc.local

What can I do ?

**Comment by UnderGreen** [comment]
/etc/rc.local is not a good entry point to fix this problem. Best way - using file inside `/etc/sysfs.d` directory.
