### ISSUE TITLE
Error with ansible v2.0.0-0.4.beta2

### ISSUE THREAD

**Issue by itkg-canne** [UnderGreen/ansible-role-mongodb#37]
I just tried to do the provisonning of my vagrant VM with the new beta version of ansible (v2.0.0-0.4.beta2) and it failed.

First, ansible failed with this error:
```
ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to have been in '/etc/ansible/roles/greendayonfire.mongodb/meta/main.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.
```
I commented the line 3 of the /etc/ansible/roles/greendayonfire.mongodb/meta/main.yml file to skip this problem and retry the operation.

It now fails on "Replication configuration" task with this error:
```
TASK [greendayonfire.mongodb : Replication configuration] **********************
fatal: [local.myapp.test]: FAILED! => {"failed": true, "msg": "ERROR! 'mongodb_replication_params' is undefined"}
```

I used the 1.4.6 version of ansible-role-mongodb.

**Comment by Incubatio** [comment]
Bug reproduced here with ansible 2.0.0.0.
Also as precised here: http://www.ansible.com/blog/ansible-2.0-launch, many ansible playbook may suffer from compatibility issues.

**Comment by jamescarr** [comment]
I have a PR for this at https://github.com/UnderGreen/ansible-role-mongodb/pull/47

**Comment by jamescarr** [comment]
@UnderGreen let me know if you need help maintaining this module. I'm more than happy to lend a hand.

**Comment by UnderGreen** [comment]
@jamescarr Sure, You can help me with developing this module. I don't have a free time to maintain it.
