### ISSUE TITLE
Port check not working if multiple bind IPs are configured

### ISSUE THREAD

**Issue by morxa** [UnderGreen/ansible-role-mongodb#46]
The port check at the end of `auth_initialization.yml` fails if the configuration contains something like

```
mongodb_conf_bind_ip: "{{ ansible_default_ipv4.address }},127.0.0.1"
```

Error message:

```
TASK: [greendayonfire.mongodb | wait MongoDB port is listening] *************** 
failed: [ci] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 192.168.0.2,127.0.0.1:27017

FATAL: all hosts have already failed -- aborting
```

This is because it uses the `mongodb_conf_bind_ip` as host IP for the port check. If the bind IP is a comma separated list, it uses the whole list as address.

On the other hand, the first port check in the same file succeeds because it uses the hard-coded localhost address `127.0.0.1`.

**Comment by UnderGreen** [comment]
Fixed
