### ISSUE TITLE
Ansible V2 meta info 

### ISSUE THREAD

**Issue by ahelal** [UnderGreen/ansible-role-mongodb#50]
In V2 ansible complains version tag in meta/main.yml

Is it possible to remove it ?

**Comment by ahelal** [comment]
Ahh sorry I see this changed but no new release has been made.
 Can you make a new release ?

**Comment by UnderGreen** [comment]
Done

**Comment by pmackay** [comment]
Should github releases appear automatically in https://galaxy.ansible.com/greendayonfire/mongodb/? It seems Galaxy is a couple of versions behind.

**Comment by UnderGreen** [comment]
No, it's problem with bad sort ordering.

**Comment by pmackay** [comment]
Ah, yes I see. Bit puzzled stil though, cos initially I was pulling the release fom Galaxy but still got a copy with the `version` in meta, so it broke my build. Had to pull from github to resolve. Not sure why.
