### ISSUE TITLE
error while evaluating conditional (systemd.stat.exists == true and mongodb_manage_service)

### ISSUE THREAD

**Issue by funkenstrahlen** [UnderGreen/ansible-role-mongodb#52]
I get the following error running the playbook:

```
ERROR! error while evaluating conditional (systemd.stat.exists == true and mongodb_manage_service): ERROR! 'dict object' has no attribute 'stat'
```

It happens at the `RUNNING HANDLER [mongodb : reload systemd]` step.

**Comment by funkenstrahlen** [comment]
When I ran the playbook the second time, the error did not occur. Strange. Do you know why?

This time I got

```
RUNNING HANDLER [mongodb : restart sysfsutils] *********************************
fatal: [xenim]: FAILED! => {"changed": false, "failed": true, "msg": "Job for sysfsutils.service failed. See 'systemctl status sysfsutils.service' and 'journalctl -xn' for details.\n"}
```

**Comment by UnderGreen** [comment]
Which OS you used?

**Comment by jvjensen** [comment]
Am experiencing the same challenge on Ubuntu 16.04, when doing ... solves this:
diff --git a/handlers/main.yml b/handlers/main.yml
index 290a74d..13267a4 100644
--- a/handlers/main.yml
+++ b/handlers/main.yml
@@ -14,7 +14,6 @@
 
 - name: reload systemd
   shell: systemctl daemon-reload
-  when: systemd.stat.exists == true and mongodb_manage_service
-
+  
 - name: restart sysfsutils
   service: name=sysfsutils state=restarted

**Comment by UnderGreen** [comment]
Fixed, I think.
