### ISSUE TITLE
Check of whether systemd is running gives wrong result

### ISSUE THREAD

**Issue by David-Gil** [UnderGreen/ansible-role-mongodb#53]
Using Ubuntu 15.10, which has systemd by default.

In install.deb.yml:
```
- name: Check if running on systemd
  command: cat /proc/1/cmdline
  register: systemd
  changed_when: false
```

The check of whether systemd is running uses the command "cat /proc/1/cmdline". This command in Ubuntu 15.10 gives the result "/sbin/init", which says nothing about systemd. The correct command would be "stat /proc/1/exe" which gives the following output:

```
vagrant@vagrant-ubuntu-wily-64:~$ sudo stat /proc/1/exe
  File: ‘/proc/1/exe’ -> ‘/lib/systemd/systemd’
  Size: 0               Blocks: 0          IO Block: 1024   symbolic link
Device: 4h/4d   Inode: 36495       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-04-07 10:21:38.438072106 +0000
Modify: 2016-04-07 10:21:38.402072106 +0000
Change: 2016-04-07 10:21:38.402072106 +0000
 Birth: -
```
With this change the "reload systemd" handler fails, as there's no "stat" in systemd register.

**Comment by UnderGreen** [comment]
Closed by #67.
