### ISSUE TITLE
Undefined Error in "create administrative user siteUserAdmin"

### ISSUE THREAD

**Issue by ysangkok** [UnderGreen/ansible-role-mongodb#55]
Using Ansible 2.0.1.0 and ansible-role-mongodb from master, I am having a problem in `tasks/auth_initialization.yml` line 22.

The error message when reaching this task is:

```
Skipping task due to undefined Error, in the future this will be a fatal error..
```

Even if I run my playbook with `-vvvvv`, I get no further output.

I tried switching from Pymongo 2.9 to 3.2.2 using mongodb_pymongo_pip_version and mongodb_pymongo_from_pip, but it seems to have no effect.

Do you know how I can learn more about this undefined error?

**Comment by UnderGreen** [comment]
Hello.
Thank you for this issue. I almost finished MongoDB 3 support. All problems like this fixed there. Just need a several days to finish TravisCI integration.

**Comment by UnderGreen** [comment]
Please test latest v2.0.0 release.
