### ISSUE TITLE
A slightly different problem creating a replica set - ServerSelectionTimeoutError

### ISSUE THREAD

**Issue by davidnoell** [UnderGreen/ansible-role-mongodb#66]
I am using greendayonfire.mongodb with only changes to the variables in defaults/main.yml.  When trying to create a replica set I get the following see the following: 
[error_msg.txt](https://github.com/UnderGreen/ansible-role-mongodb/files/477987/error_msg.txt)

=============== BEGIN =============== 
TASK [greendayonfire.mongodb : Ensure service is started] **********************
ok: [xxx.xxx.xxx.250]

ok: [xxx.xxx.xxx.81]
ok: [xxx.xxx.xxx.111]

TASK [greendayonfire.mongodb : Set fact about wait_for host address] ***********
skipping: [xxx.xxx.xxx.111]
skipping: [xxx.xxx.xxx.81]
skipping: [xxx.xxx.xxx.250]

TASK [greendayonfire.mongodb : Wait when mongodb is started] *******************
ok: [xxx.xxx.xxx.81]
ok: [xxx.xxx.xxx.250]
ok: [xxx.xxx.xxx.111]

TASK [greendayonfire.mongodb : Include replication and auth configuration] *****
skipping: [xxx.xxx.xxx.111]
skipping: [xxx.xxx.xxx.81]
skipping: [xxx.xxx.xxx.250]

TASK [greendayonfire.mongodb : Include replication configuration] **************
included: /Users/your_name_here/Documents/DataScience/finalproj/roles/greendayonfire.mongodb/tasks/replication.yml for xxx.xxx.xxx.111, xxx.xxx.xxx.81, xxx.xxx.xxx.250

TASK [greendayonfire.mongodb : Replication configuration] **********************
skipping: [xxx.xxx.xxx.81] => (item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'xxx.xxx.xxx.81'}) 
skipping: [xxx.xxx.xxx.111] => (item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'xxx.xxx.xxx.81'}) 
skipping: [xxx.xxx.xxx.250] => (item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'xxx.xxx.xxx.81'}) 
skipping: [xxx.xxx.xxx.81] => (item={u'host_port': 27017, u'host_type': u'arbiter', u'host_name': u'xxx.xxx.xxx.250'}) 
skipping: [xxx.xxx.xxx.111] => (item={u'host_port': 27017, u'host_type': u'arbiter', u'host_name': u'xxx.xxx.xxx.250'}) 
skipping: [xxx.xxx.xxx.250] => (item={u'host_port': 27017, u'host_type': u'arbiter', u'host_name': u'xxx.xxx.xxx.250'}) 

TASK [greendayonfire.mongodb : Replication configuration without auth] *********
failed: [xxx.xxx.xxx.81](item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'xxx.xxx.xxx.81'}) => {"failed": true, "item": {"host_name": "xxx.xxx.xxx.81", "host_port": 27017, "host_type": "replica"}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_z9H610/ansible_module_mongodb_replication.py\", line 410, in <module>\r\n    main()\r\n  File \"/tmp/ansible_z9H610/ansible_module_mongodb_replication.py\", line 373, in main\r\n    client['admin'].command('replSetInitiate', config)\r\n  File \"/usr/local/lib/python2.7/dist-packages/pymongo/database.py\", line 478, in command\r\n    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py\", line 798, in _socket_for_reads\r\n    with self._get_socket(read_preference) as sock_info:\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py\", line 762, in _get_socket\r\n    server = self._get_topology().select_server(selector)\r\n  File \"/usr/local/lib/python2.7/dist-packages/pymongo/topology.py\", line 210, in select_server\r\n    address))\r\n  File \"/usr/local/lib/python2.7/dist-packages/pymongo/topology.py\", line 186, in select_servers\r\n    self._error_message(selector))\r\npymongo.errors.ServerSelectionTimeoutError: xxx.xxx.xxx.111:27017: timed out\r\n", "msg": "MODULE FAILURE", "parsed": false}
failed: [xxx.xxx.xxx.250](item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'xxx.xxx.xxx.81'}) => {"failed": true, "item": {"host_name": "xxx.xxx.xxx.81", "host_port": 27017, "host_type": "replica"}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_b7AAzE/ansible_module_mongodb_replication.py\", line 410, in <module>\r\n    main()\r\n  File \"/tmp/ansible_b7AAzE/ansible_module_mo
=============== BEGIN =============== 

To get the replica set configured I have the following in defaults/main.yml
[defaults_main.yml.txt](https://github.com/UnderGreen/ansible-role-mongodb/files/477985/defaults_main.yml.txt)

`## replication Options`
mongodb_replication_replset: "rs0"                # Enable replication <setname>[/<optionalseedhostlist>]
mongodb_replication_replindexprefetch: "all"      # specify index prefetching behavior (if secondary) [none|_id_only|all]
mongodb_replication_oplogsize: 1024               # specifies a maximum size in megabytes for the replication operation log

`# It's a 'master' node`
mongodb_login_host: xxx.xxx.xxx.111

```
# mongodb_replication_params should be configured on each replica set node
mongodb_replication_params:
```
- { host_name: "xxx.xxx.xxx.81", host_port: "{{ mongodb_net_port }}", host_type: replica }
- { host_name: "xxx.xxx.xxx.250", host_port: "{{ mongodb_net_port }}", host_type: arbiter }
  # host_type can be replica(default) and arbiter

My inventory.txt file is as follows:
[mongo_master]
xxx.xxx.xxx.111 mongodb_master=True # it is't a really master of MongoDB replica set,
                                 # use this variable for replica set init only
                                 # or when master is moved from initial master node

[mongo_replicas]
xxx.xxx.xxx.81
xxx.xxx.xxx.250

[mongo:children]
mongo_master
mongo_replicas

Everything else is working great!  Any help or just pointing me in the right direction would be wonderful!!

Thanks,

David

**Comment by UnderGreen** [comment]
@davidnoell Can you try with the latest master. I've found the way to fix that issue.
