### ISSUE TITLE
fail to create first user when auth enabled

### ISSUE THREAD

**Issue by carlislemc** [UnderGreen/ansible-role-mongodb#69]
Using mongodb 3.2.9, https://github.com/UnderGreen/ansible-role-mongodb/blob/master/library/mongodb_user.py fails on the call to user_find when trying to add the first admin user (since you can't list users before you've added the first admin).

One solution might be to have user_find return false if it throws an exception (that's what I've done to get past this); however, if you want to preserve the exception in user_find, then perhaps you could catch the exception at line 334         uinfo = user_find(client, user, db_name), and allow it to proceed with uinfo = False if db_name is admin.

**Comment by UnderGreen** [comment]
@carlislemc can you try with the latest master?
