### ISSUE TITLE
Request: using alternative mongodb repository

### ISSUE THREAD

**Issue by Zhomart** [UnderGreen/ansible-role-mongodb#74]
Mongodb's official instructions use `echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
`

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

**Comment by UnderGreen** [comment]
https://github.com/UnderGreen/ansible-role-mongodb/blob/master/vars/Debian.yml#L6
https://github.com/UnderGreen/ansible-role-mongodb/blob/master/vars/Ubuntu.yml#L6
It's it?

**Comment by Zhomart** [comment]
Ok, I don't know how I missed it :) Thank you
