### ISSUE TITLE
chown failed: failed to lookup user mongodb 

### ISSUE THREAD

**Issue by ghskangarani** [UnderGreen/ansible-role-mongodb#75]
I got this error when I trying to install mongo db for first time
<img width="1272" alt="screen shot 2017-03-01 at 9 01 26 am" src="https://cloud.githubusercontent.com/assets/11487972/23447082/b3aa7236-fe5d-11e6-9ee2-2242d7936b9e.png">

**Comment by UnderGreen** [comment]
Sorry. Didn't have time to maintain role. Do you still have the problem?
