### ISSUE TITLE
CentOS/RHEL Support Release

### ISSUE THREAD

**Issue by justinsaliba** [UnderGreen/ansible-role-mongodb#84]
Hi, I was wondering when the next release is expected to be?

At the moment our Ansible Galaxy requirements YML file has a direct reference to origin/master which is quite risky since it's essentially a moving version. I see the latest release is v2.1.0 from June, but new features / bugfixes have been introduced since then.

Our YML file looks like this:
```
- src: https://github.com/UnderGreen/ansible-role-mongodb
  version: origin/master
```

Thanks in advance,
Justin

**Comment by UnderGreen** [comment]
Done
