### ISSUE TITLE
Update support matrix?

### ISSUE THREAD

**Issue by pmackay** [UnderGreen/ansible-role-mongodb#85]
The MongoDB support matrix at the top of the README shows a cross for Ubuntu 14.04 and Ubuntu 12.04 for Mongo 3.4. But below that in the config example it says:

> I will recommend you to use latest version of MongoDB.
>mongodb_version: "3.4"

Is Mongo 3.4 properly tested on Ubuntu 14 and 12? If so, does the grid need updating?

**Comment by UnderGreen** [comment]
Done
