### ISSUE TITLE
Amazon RHEL ami has ansible_distribution == RedHat (instead of Red Hat Enterprise Linux)

### ISSUE THREAD

**Issue by dbsrv** [UnderGreen/ansible-role-mongodb#86]
Amazon RHEL (ami-9fa343e7) has ansible_distribution == RedHat (instead of Red Hat Enterprise Linux). This causes skipping agent download in **mms-agent.yml**

Original:
- name: Download MMS Agent (RHEL)
  get_url: url={{mongodb_mms_agent_pkg}} dest={{mongodb_storage_dbpath}}/mms-agent.rpm
  register: mongodb_mms_agent_loaded
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

Fix could be:
- name: Download MMS Agent (RHEL)
  get_url: url={{mongodb_mms_agent_pkg}} dest={{mongodb_storage_dbpath}}/mms-agent.rpm
  register: mongodb_mms_agent_loaded
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'

**Comment by UnderGreen** [comment]
@dbsrv fixed on the latest master
