### ISSUE TITLE
exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [UnderGreen/ansible-role-mongodb#87]
System Details:
[root@mongo03 ~]# hostnamectl
   Static hostname: mongo03.ubernet.local
Transient hostname: mongo03
         Icon name: computer
        Machine ID: e092cc00cc8b41be85aed1b37e13451b
           Boot ID: 31abfb07c6d64efba15142e7aefea271
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.1.el7.x86_64
      Architecture: x86-64
[root@mongo03 ~]#

This fixes the issue: chcon -R --reference=/var/lib/mongo /data/db

https://stackoverflow.com/questions/42446931/mongodb-exception-in-initandlisten-20-attempted-to-create-a-lock-file-on-a-rea

**Comment by UnderGreen** [comment]
I think it is not a problem with role. I'm not interested to handle issues with SELinux. Should be a part of specific SELinux role.
