### ISSUE TITLE
Replication failing when authentication is enabled

### ISSUE THREAD

**Issue by AswinKakarot** [UnderGreen/ansible-role-mongodb#89]
I was trying out your ansible role. I'm running MongoDB 3.4. Everything works like clock work without authentication. But when I enabled authentication it is failing. I did my own debugging and found out this might be because I'm not specifying --authenticationDatabase option. Is there an option to add it to the vars? Thanks in advance. 

Error:

> failed: [hostname-1] (item={u'host_port': 27017, u'host_type': u'replica', u'host_name': u'hostname-1'}) => {"changed": false, "item": {"host_name": "hostname-1", "host_port": 27017, "host_type": "replica"}, "msg": "Unable to initiate replica set: not authorized on admin to execute command { replSetInitiate: { _id: \"clusterName\", members: [ { host: \"hostname-1:27017\", _id: 0 } ] } }"}

**Comment by ctlaux** [comment]
Would you mind sharing what you did to solve this problem?

**Comment by CptMaumau** [comment]
Any fix for this one?

**Comment by AswinKakarot** [comment]
You need to specify the following variables
**mongodb_user_admin_name**
**mongodb_user_admin_password**
**mongodb_root_admin_name**
**mongodb_root_admin_password**
**mongodb_login_host**

**Comment by AswinKakarot** [comment]
The replication Pt.1 Will most probably fail but Pt.2 will succeed.
