### ISSUE TITLE
MongoDB service name

### ISSUE THREAD

**Issue by seprob** [UnderGreen/ansible-role-mongodb#91]
In Ubuntu 16 LTS when I have installed "mongodb-org" packages my MongoDB service name is called "mongodb" not "mongod".

**Comment by UnderGreen** [comment]
It's weird. Just added test suite for 16.04 and all works fine.

**Comment by UnderGreen** [comment]
@seprob Can you retest your setup with the latest master?

**Comment by seprob** [comment]
I checked it again but this time on virtual machine with using Vagrant: service name is called "mongod" so it's correct. I cannot test it on the machine where it's not correct so for now I think we can close this issue.
